steps:

- id: 'deploy service'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'ui', '--image', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}', '--region', '${_REGION}', '--platform', 'managed', '--set-env-vars', 'HOST=${_HOST},DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY}', '--add-cloudsql-instances', '${_PROJECT_ID}:${_REGION}:${_DB_INSTANCE_NAME}','--command', 'entrypoint.sh','--args', 'serve']

substitutions:
  _PROJECT_ID: mywriters
  _REGION: europe-west1
  _SERVICE_NAME: ui
  _DB_INSTANCE_NAME: ui-db

