# Generated by Django 3.1.5 on 2021-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarr', '0003_remove_feed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='rss',
            field=models.TextField(null=True),
        ),
    ]
