# Generated by Django 3.1.5 on 2021-01-08 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarr', '0004_feed_rss'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='site_url',
            field=models.TextField(help_text='URL of the HTML site', unique=True, validators=[django.core.validators.URLValidator()], verbose_name='Site URL'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.TextField(help_text='Published title of the feed', unique=True),
        ),
    ]
