# Generated by Django 3.1.5 on 2021-01-10 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarr', '0005_auto_20210108_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='site_url',
            field=models.TextField(help_text='URL of the HTML site', validators=[django.core.validators.URLValidator()], verbose_name='Site URL'),
        ),
    ]
