# Generated by Django 3.1.4 on 2020-12-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywriters', '0002_catalogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='writer',
            new_name='name',
        ),
    ]
