# Generated by Django 3.1.4 on 2020-12-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarr', '0003_remove_feed_users'),
        ('mywriters', '0004_auto_20201229_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeeds',
            name='feeds',
            field=models.ManyToManyField(to='yarr.Feed'),
        ),
    ]
