# Generated by Django 3.1.5 on 2021-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywriters', '0005_userfeeds_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('rss', models.TextField()),
            ],
        ),
    ]
