steps:

- id: "apply migrations"
  name: "gcr.io/google-appengine/exec-wrapper"
  args:
    - "-i"
    - "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:latest"
    - "-s"
    - "${_PROJECT_ID}:${_REGION}:${_DB_INSTANCE_NAME}"
    - "-e"
    - "DATABASE_URL=${_DATABASE_URL}"
    - '-e'
    - 'SECRET_KEY=${_SECRET_KEY}'
    - '-e'
    - 'SUPERUSER_PASSWORD=${_SUPERUSER_PASSWORD}'
    - '-e'
    - 'TEST_USER_PASSWORD=${_TEST_USER_PASSWORD}'
    - "--"
    - "migrate"
    
substitutions:
  _PROJECT_ID: mywriters
  _DB_INSTANCE_NAME: ui-db
  _REGION: europe-west1
  _SERVICE_NAME: ui

images:
- gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}
