# Generated by Django 3.1.4 on 2020-12-21 21:02

# env var accessdef forwards_func(apps, schema_editor):
import os
from django.contrib.auth.models import User     # where User lives
from django.db import migrations, models
import os

from django.db import migrations

from django.db.migrations.state import StateApps
from django.contrib.auth.models import User


def createsuperuser(apps: StateApps, schema_editor) -> None: 
    User.objects.create_superuser("admin", password=os.getenv("SUPERUSER_PASSWORD"))
    User.objects.create_user(
        username='test', email='test@test.com', password=os.getenv("TEST_USER_PASSWORD"))


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [migrations.RunPython(createsuperuser)]
