steps:

- id: 'build image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}', '.']
  dir: 'ui'

- id: 'push image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}']

- id: "apply migrations"
  name: "gcr.io/google-appengine/exec-wrapper"
  args:
    [
      "-i",
      "gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}",
      "-s",
      "${_PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
      "-e",
      "DATABASE_URL=${_DATABASE_URL}",
      '-e',
      'SECRET_KEY=${_SECRET_KEY}',
      '-e',
      'SUPERUSER_PASSWORD=${_SUPERUSER_PASSWORD}',
      "--",
      "python",
      "manage.py",
      "migrate",
    ]

- id: 'deploy service'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'ui', '--image', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}', '--region', '${_REGION}', '--platform', 'managed', '--set-env-vars', 'HOST=${_HOST},DATABASE_URL=${_DATABASE_URL},SECRET_KEY=${_SECRET_KEY}']

substitutions:
  _PROJECT_ID: mywriters
  _INSTANCE_NAME: django-instance
  _REGION: europe-west1
  _SERVICE_NAME: ui


images:
- gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}
